"""empty message

Revision ID: 29fd331b4901
Revises: 6edcd2472b8b
Create Date: 2021-02-14 23:11:30.380108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29fd331b4901'
down_revision = '6edcd2472b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.UnicodeText(), nullable=False),
    sa.Column('title', sa.Unicode(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Integer(), nullable=False),
    sa.Column('destination', sa.UnicodeText(), nullable=False),
    sa.ForeignKeyConstraint(['source'], ['pages.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('links')
    op.drop_table('pages')
    # ### end Alembic commands ###
